# importer files
require 'import_helper'
require 'importers/c32/advance_directive_c32_importer'
require 'importers/c32/allergy_c32_importer'
require 'importers/c32/registration_information_c32_importer'
require 'importers/c32/condition_c32_importer'
require 'importers/c32/encounter_c32_importer'
require 'importers/c32/medication_c32_importer'
require 'importers/c32/patient_c32_importer'
require 'importers/c32/result_c32_importer'
require 'importers/c32/vital_sign_c32_importer'
require 'importers/c32/support_c32_importer'
require 'importers/c32/insurance_provider_c32_importer'
require 'importers/c32/immunization_c32_importer'
require 'importers/c32/healthcare_provider_c32_importer'
require 'importers/c32/address_c32_importer'
require 'importers/c32/telecom_c32_importer'
require 'importers/c32/person_name_c32_importer'
